module.exports = {
  content: [
    './client/**/*.html',
    './client/**/*.js',
    './client/**/*.jsx',
    './imports/**/*.js',
    './imports/**/*.jsx',
    './imports/**/*.html',
    './server/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          title: '#f2f8fd',
          paragraph: '#cbd5e1',
          bgFirst: '#112A46',
          bgSec: '#1c3b57',
          textPrimary: '#e2e8f0',
          textSecondary: '#94a3b8',
          textAccent: '#38bdf8',
          bgPrimary: '#0f172a',
          bgSecondary: '#1e293b',
          bgAccent: '#334155',
          borderPrimary: '#64748b',
          borderSecondary: '#475569',
          linkDefault: '#38bdf8',
          linkHover: '#0ea5e9',
          buttonPrimary: '#3b82f6',
          buttonSecondary: '#2563eb',
          buttonHover: '#1d4ed8',
          buttonText: '#ffffff',
          iconDefault: '#e2e8f0',
          iconHover: '#38bdf8',
          inputBackground: '#1e293b',
          inputText: '#f1f5f9',
          inputBorder: '#475569',
          shadowPrimary: 'rgba(0, 0, 0, 0.75)',
          shadowSecondary: 'rgba(0, 0, 0, 0.5)',
        },
        light: {
          title: '#1f2937',
          paragraph: '#4b5563',
          bgFirst: '#f9fafb',
          bgSec: '#e5e7eb',
          textPrimary: '#111827',
          textSecondary: '#6b7280',
          textAccent: '#2563eb',
          bgPrimary: '#ffffff',
          bgSecondary: '#f3f4f6',
          bgAccent: '#e0e7ff',
          borderPrimary: '#d1d5db',
          borderSecondary: '#e5e7eb',
          linkDefault: '#2563eb',
          linkHover: '#1d4ed8',
          buttonPrimary: '#3b82f6',
          buttonSecondary: '#2563eb',
          buttonHover: '#1d4ed8',
          buttonText: '#ffffff',
          iconDefault: '#4b5563',
          iconHover: '#2563eb',
          inputBackground: '#ffffff',
          inputText: '#111827',
          inputBorder: '#d1d5db',
          shadowPrimary: 'rgba(0, 0, 0, 0.1)',
          shadowSecondary: 'rgba(0, 0, 0, 0.05)',
        }
      }
    },
  },
  plugins: [

  ],
}
